// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDotip55TSnodHbTTkERDJx1z0SGPZpgm4',
    appId: '1:245664334907:web:7cb218198261233db5081e',
    messagingSenderId: '245664334907',
    projectId: 'flomart-eas-31a05',
    authDomain: 'flomart-eas-31a05.firebaseapp.com',
    storageBucket: 'flomart-eas-31a05.firebasestorage.app',
    measurementId: 'G-S29WYH9WPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv1iXXLpkVqaTN7oCitrF2tPoyjiAMvhw',
    appId: '1:245664334907:android:029dcdb1963de75bb5081e',
    messagingSenderId: '245664334907',
    projectId: 'flomart-eas-31a05',
    storageBucket: 'flomart-eas-31a05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ5_UF7V5BBW5X3fQ84RsLiY9bcUIkP8A',
    appId: '1:245664334907:ios:19e74cfb0062b54eb5081e',
    messagingSenderId: '245664334907',
    projectId: 'flomart-eas-31a05',
    storageBucket: 'flomart-eas-31a05.firebasestorage.app',
    iosBundleId: 'com.example.flomartPemmob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ5_UF7V5BBW5X3fQ84RsLiY9bcUIkP8A',
    appId: '1:245664334907:ios:19e74cfb0062b54eb5081e',
    messagingSenderId: '245664334907',
    projectId: 'flomart-eas-31a05',
    storageBucket: 'flomart-eas-31a05.firebasestorage.app',
    iosBundleId: 'com.example.flomartPemmob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDotip55TSnodHbTTkERDJx1z0SGPZpgm4',
    appId: '1:245664334907:web:83cda103a550ad1eb5081e',
    messagingSenderId: '245664334907',
    projectId: 'flomart-eas-31a05',
    authDomain: 'flomart-eas-31a05.firebaseapp.com',
    storageBucket: 'flomart-eas-31a05.firebasestorage.app',
    measurementId: 'G-BT77SGV20N',
  );
}
