// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm4mcGjsP09_Rxja-xf6YkygPO6rFgTfQ',
    appId: '1:885630439645:web:9f25f8a6c6644aea214b34',
    messagingSenderId: '885630439645',
    projectId: 'flomart-eas-cdf44',
    authDomain: 'flomart-eas-cdf44.firebaseapp.com',
    storageBucket: 'flomart-eas-cdf44.firebasestorage.app',
    measurementId: 'G-Z6M7TZW655',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXWMf1EHRR7YX2j-dLYROzIdZgBiAzf2E',
    appId: '1:885630439645:android:374749d916806fbe214b34',
    messagingSenderId: '885630439645',
    projectId: 'flomart-eas-cdf44',
    storageBucket: 'flomart-eas-cdf44.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFSUH23k_f5vmWsIvzWNhddhnHVP4ymJ8',
    appId: '1:885630439645:ios:b7795c3ded2e0f2f214b34',
    messagingSenderId: '885630439645',
    projectId: 'flomart-eas-cdf44',
    storageBucket: 'flomart-eas-cdf44.firebasestorage.app',
    iosBundleId: 'com.example.flomartPemmob',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFSUH23k_f5vmWsIvzWNhddhnHVP4ymJ8',
    appId: '1:885630439645:ios:b7795c3ded2e0f2f214b34',
    messagingSenderId: '885630439645',
    projectId: 'flomart-eas-cdf44',
    storageBucket: 'flomart-eas-cdf44.firebasestorage.app',
    iosBundleId: 'com.example.flomartPemmob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm4mcGjsP09_Rxja-xf6YkygPO6rFgTfQ',
    appId: '1:885630439645:web:dc70e5b477c991aa214b34',
    messagingSenderId: '885630439645',
    projectId: 'flomart-eas-cdf44',
    authDomain: 'flomart-eas-cdf44.firebaseapp.com',
    storageBucket: 'flomart-eas-cdf44.firebasestorage.app',
    measurementId: 'G-ZEPT8TSN0Z',
  );
}
